server:
  port: 20000 # Registry center port

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false # mark itself as a center server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server
