language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

before_install:
  - cd cache-client
  - mvn install -DskipTests
  - cd ..

install:
  - mvn install -DskipTests

script: mvn test

after_script:
  - cd cache-demo
  - mvn package -DskipTests
