language: java

branches:
  only:
    - master

jdk:
  - openjdk11

before_install: chmod 775 ./script/*

install: ./script/build_cache.sh

script: echo "All install done."

after_script: ./script/build_demo.sh
