# Application port
server:
  port: 9527

# Register to the spring cloud cluster
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

# Application name
spring:
  application:
    name: cache-client

# TODO: Optimize the style of the configuration
# Hystrix configuration
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000

# Feign client configuration
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

## XXCache configuration ##
xxcache:
  route-name: cache-route
  service-prefix: /cache-service
  client:
    readTimeout: 2000
    connectTimeout: 2000
    writeTimeout: 5000
    pool:
      maxIdleConnection: 10
      keepAliveDuration: 300

