eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka
server:
  port: 8080

spring:
  application:
    name: cache-route

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

zuul:
  routes:
    cache-service:
      path: /cache-service/**
      serviceId: cache-service

load-balance:
  virtual-node: 10

ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  readTimeout: 2000
  connectTimeout: 2000