eureka:
  client:
    serviceUrl:
      # Url fetching all the instances of the cache service
      registryUrl: http://localhost:20000/service-instances/CACHE-SERVICE
      defaultZone: http://localhost:20000/eureka
server:
  port: 8080

spring:
  application:
    name: cache-route
  rabbitmq:
    host: localhost
    username: admin
    password: admin

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

zuul:
  routes:
    cache-service:
      path: /cache-service/**
      serviceId: cache-service

loadBalance:
  virtualNode: 10
  interval: 120000 # in millisecond

ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  readTimeout: 4000
  connectTimeout: 4000