server:
  port: 20001 # -Dserver.port=xxx
  
spring:
  application:
    name: cache-service
  rabbitmq:
    host: localhost
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka


# CacheManager/Cache/CacheExpiration configurations
xxcache:
  name: CacheManager
  caches:
    - cacheName: cache1
      cacheType: basic
      expiration:
        strategy: noop

    - cacheName: cache2
      cacheType: approximate_lru
      maxSize: 1024
      expiration:
        expiration: 3600
        strategy: lazy

    - cacheName: cache3
      cacheType: approximate_lru
      maxSize: 2048
      expiration:
        expiration: 1800
        strategy: schedule
        initDelay: 60
        interval: 300